/* VaultDex — card catalog client (TCGdex, https://api.tcgdex.net).
 * All card data comes from here; nothing is invented locally.
 * TCGdex needs no API key and serves static JSON, so it doesn't
 * rate-limit or throw 500s the way the old provider did.
 * The public App.tcg interface is unchanged, so the views don't care
 * where the data comes from.
 */
(function () {
  window.App = window.App || {};

  var API_ROOT = "https://api.tcgdex.net/v2";

  var LS_INDEX = "vd_tcgdex_index_v1"; // {at, cards:[{id,localId,name}]}
  var LS_SETS = "vd_tcgdex_sets_v2";   // {at, sets:[...]} (v2: lang+era fields)
  var CACHE_TTL = 7 * 24 * 3600 * 1000; // refresh weekly; new sets drop often
  var DETAIL_CAP = 400; // max card details fetched for filtered searches

  /* App-level set ids: English sets use the raw TCGdex id; Japanese sets
   * are prefixed "ja-" because a few ids (e.g. neo1) exist in both
   * languages. parseSetId splits the app id back into language + id. */
  function parseSetId(appId) {
    if (App.util.isJa(appId)) return { lang: "ja", id: appId.slice(3) };
    return { lang: "en", id: appId };
  }
  function appSetId(lang, id) {
    return lang === "ja" ? "ja-" + id : id;
  }

  /* Local catalog snapshot (data/tcgdex/, generated by
   * scripts/snapshot-tcgdex.py). Served from the app itself so catalog
   * reads never touch the network; live API is the fallback for sets
   * added after the snapshot was taken. */
  var SNAP = "/data/tcgdex";
  /* fetch() with a hard timeout: a stalled request must reject instead of
   * hanging the page forever. A hung snapshot fetch once left set pages
   * blank (no header, no grid, no error) because every later render step
   * awaited it. Callers already catch failures and fall back or show an
   * error state — they just never got the chance while the promise hung. */
  var FETCH_TIMEOUT_MS = 20000;
  /* Shared: App.util.fetchWithTimeout (js/util.js). */

  async function snapJson(rel) {
    var res = await App.util.fetchWithTimeout(SNAP + "/" + rel, null, FETCH_TIMEOUT_MS);
    if (!res.ok) throw new Error("no snapshot: " + rel);
    return res.json();
  }

  function ApiError(message, status) {
    this.name = "ApiError";
    this.message = message;
    this.status = status;
  }
  ApiError.prototype = Object.create(Error.prototype);

  async function req(path, lang) {
    var base = API_ROOT + "/" + (lang || "en");
    var res;
    try {
      res = await App.util.fetchWithTimeout(base + path, null, FETCH_TIMEOUT_MS);
    } catch {
      throw new ApiError("Network error — check your connection and try again.", 0);
    }
    if (!res.ok) {
      throw new ApiError("Card catalog error (HTTP " + res.status + ").", res.status);
    }
    return res.json();
  }

  /* Shared: App.util.normNumber (js/util.js) — "001" -> "1", so padded
   * TCGdex numbers match unpadded ones everywhere (PkmnPrices matching,
   * owned-row keys, display). */
  var normNumber = App.util.normNumber;

  function titleCase(s) {
    return String(s || "").toLowerCase().replace(/(^|[\s-])(\w)/g, function (m, p1, p2) {
      return p1 + p2.toUpperCase();
    });
  }

  function num(v) { return typeof v === "number" ? v : null; }

  /* TCGdex tcgplayer pricing keys are normal/holofoil/reverseHolofoil
   * (occasionally shortened to holo/reverse); normalize to the app's keys. */
  var PRICE_KEYS = [
    ["normal", "normal"],
    ["holofoil", "holofoil"],
    ["holofoil", "holo"],
    ["reverseHolofoil", "reverseHolofoil"],
    ["reverseHolofoil", "reverse"]
  ];
  function pricesOf(detail) {
    var tp = detail && detail.pricing && detail.pricing.tcgplayer;
    if (!tp) return null;
    var cur = detail.pricing.currency || null;
    var out = {};
    PRICE_KEYS.forEach(function (pair) {
      var src = tp[pair[1]];
      if (src && typeof src === "object" && !out[pair[0]]) {
        out[pair[0]] = {
          low: num(src.lowPrice),
          mid: num(src.midPrice),
          high: num(src.highPrice),
          market: num(src.marketPrice),
          currency: cur
        };
      }
    });
    return out;
  }

  /* Normalize a TCGdex card (set-list summary or full detail) into the
   * shape the app's views expect. Summaries lack rarity/artist/pricing;
   * callers can enrich via getDetails(). */
  function normCard(c, setId, setName, lang) {
    var img = c.image || "";
    return {
      id: c.id,
      name: c.name,
      number: normNumber(c.localId),
      rarity: c.rarity ? titleCase(c.rarity) : null,
      artist: c.illustrator || null,
      supertype: c.category ? titleCase(c.category) : null,
      types: c.types || [],
      hp: c.hp != null ? String(c.hp) : null,
      images: {
        /* Japanese snapshots carry direct Bulbagarden Archives URLs
         * (imageSmall = 400px thumb, imageLarge = full scan); TCGdex
         * cards use the image base path with /low.png and /high.png. */
        small: c.imageSmall || (img ? img + "/low.png" : null),
        large: c.imageLarge || (img ? img + "/high.png" : null)
      },
      set: { id: setId, name: setName, lang: lang || "en" },
      tcgplayer: c.pricing ? { prices: pricesOf(c) } : null,
      /* Currency of baked catalog prices ("USD" default; Japanese cards
       * may carry EUR Cardmarket prices when no USD row exists). */
      priceCurrency: (c.pricing && c.pricing.currency) || null,
      variants_detailed: c.variants_detailed || null,
      stage: c.stage || null,
      attacks: c.attacks,
      weaknesses: c.weaknesses
    };
  }

  /* ---------------- sets ---------------- */

  /* TCGdex asset URLs for set logos/symbols are extensionless and return
   * an HTML help page as-is; appending .png yields the real image. */
  function assetUrl(u) {
    if (!u) return null;
    return /\.\w+$/.test(String(u).split("?")[0]) ? u : u + ".png";
  }

  var setsCache = null;
  function setsFromStorage() {
    try {
      var raw = localStorage.getItem(LS_SETS);
      if (!raw) return null;
      var p = JSON.parse(raw);
      if (p && Array.isArray(p.sets) && p.sets.length && (Date.now() - (p.at || 0)) < CACHE_TTL) return p.sets;
    } catch { /* corrupted: refetch below */ }
    return null;
  }

  /* Newest sets first (the API returns chronological order). The list has
   * no release dates, so logos + names + counts are all the tab needs. */
  function mapSetEntry(s) {
    var lang = s.lang || "en";
    return {
      appId: appSetId(lang, s.id),
      id: s.id,
      lang: lang,
      name: s.name,
      series: s.series || null,
      eraRank: s.eraRank != null ? s.eraRank : 999,
      setRank: s.setRank != null ? s.setRank : 999,
      releaseDate: null,
      printedTotal: s.printedTotal,
      total: s.total,
      images: { logo: assetUrl(s.logo), symbol: assetUrl(s.symbol) }
    };
  }

  async function getSets() {
    if (setsCache) return setsCache;
    try {
      // Snapshot lists are pre-sorted: newest era first, newest set first.
      var en = await snapJson("sets.json");
      var out = en.map(mapSetEntry);
      try {
        var ja = await snapJson("sets-ja.json");
        out = out.concat(ja.map(mapSetEntry));
      } catch { /* Japanese list not snapshotted yet */ }
      setsCache = out;
      return setsCache;
    } catch { /* no snapshot: live API below */ }
    var cached = setsFromStorage();
    if (cached) { setsCache = cached; return cached; }
    var arr = await req("/sets");
    setsCache = arr.slice().reverse().map(function (s) {
      return mapSetEntry({
        id: s.id, name: s.name, lang: "en",
        printedTotal: s.cardCount && s.cardCount.official,
        total: s.cardCount && s.cardCount.total,
        logo: s.logo, symbol: s.symbol
      });
    });
    try { localStorage.setItem(LS_SETS, JSON.stringify({ at: Date.now(), sets: setsCache })); } catch { /* quota: skip */ }
    return setsCache;
  }

  function setSnapPath(appId) {
    var p = parseSetId(appId);
    return p.lang === "ja"
      ? "sets/ja/" + encodeURIComponent(p.id) + ".json"
      : "sets/" + encodeURIComponent(p.id) + ".json";
  }

  async function getSet(appId) {
    var p = parseSetId(appId);
    try {
      var snap = await snapJson(setSnapPath(appId));
      var sh = snap.set || {};
      return {
        appId: appId,
        id: sh.id,
        lang: sh.lang || p.lang,
        name: sh.name,
        series: sh.series || null,
        releaseDate: sh.releaseDate || null,
        printedTotal: sh.printedTotal,
        total: sh.total,
        images: { logo: assetUrl(sh.logo), symbol: assetUrl(sh.symbol) }
      };
    } catch { /* no snapshot for this set: live API below */ }
    var s = await req("/sets/" + encodeURIComponent(p.id), p.lang);
    var out = {
      appId: appId,
      id: s.id,
      lang: p.lang,
      name: s.name,
      series: s.serie && s.serie.name,
      releaseDate: s.releaseDate || null,
      printedTotal: s.cardCount && s.cardCount.official,
      total: s.cardCount && s.cardCount.total,
      images: { logo: assetUrl(s.logo), symbol: assetUrl(s.symbol) }
    };
    if (p.lang === "ja") {
      /* Live TCGdex Japanese set metadata still has the Japanese name and
       * no artwork. Overlay the community English name, cached art, and era
       * label from the local set list so headers look right even before the
       * per-set snapshot exists. */
      try {
        var sets = await getSets();
        var match = null;
        for (var i = 0; i < sets.length; i++) {
          if (sets[i].lang === "ja" && String(sets[i].id) === String(p.id)) { match = sets[i]; break; }
        }
        if (match) {
          out.name = match.name || out.name;
          out.series = match.series || out.series;
          out.images = {
            logo: match.images && match.images.logo,
            symbol: match.images && match.images.symbol
          };
        }
      } catch { /* keep the live metadata */ }
    }
    return out;
  }

  /* ---------------- set cards ---------------- */

  var setCardsCache = {}; // setId -> [normCards, number-sorted]
  function sortCards(list) {
    list.sort(function (a, b) {
      var an = parseInt(a.number, 10), bn = parseInt(b.number, 10);
      if (!isNaN(an) && !isNaN(bn) && an !== bn) return an - bn;
      return String(a.number).localeCompare(String(b.number));
    });
    return list;
  }
  async function getSetCardList(appId) {
    if (setCardsCache[appId]) return setCardsCache[appId];
    var p = parseSetId(appId);
    try {
      // Snapshot cards are trimmed details: no enrichment fetches needed.
      var snap = await snapJson(setSnapPath(appId));
      var snapCards = (snap.cards || []).map(function (c) {
        return normCard(c, (snap.set && snap.set.id) || p.id, (snap.set && snap.set.name) || "", p.lang);
      });
      setCardsCache[appId] = sortCards(snapCards);
      return setCardsCache[appId];
    } catch { /* no snapshot for this set: live API below */ }
    var s = await req("/sets/" + encodeURIComponent(p.id), p.lang);
    var list = (s.cards || []).map(function (c) { return normCard(c, s.id, s.name, p.lang); });
    setCardsCache[appId] = sortCards(list);
    return setCardsCache[appId];
  }

  async function getSetCards(appId, page, pageSize, opts) {
    page = page || 1;
    pageSize = pageSize || 48;
    var list = await getSetCardList(appId);
    // Optional in-set filter: card name (substring) or exact card number.
    var q = opts && opts.name ? String(opts.name).trim().toLowerCase() : "";
    if (q) {
      list = list.filter(function (c) {
        return (c.name || "").toLowerCase().indexOf(q) !== -1 ||
          String(c.number || "").toLowerCase() === q;
      });
    }
    // Optional rarity filter: exact rarity label ("All rarities" = "").
    var rar = opts && opts.rarity ? String(opts.rarity) : "";
    if (rar) {
      list = list.filter(function (c) { return (c.rarity || "Unknown") === rar; });
    }
    // Optional sort: "number" (default), "priceDesc", "priceAsc", "name".
    // Unpriced cards always sort last, whichever direction prices run.
    var sort = (opts && opts.sort) || "number";
    if (sort !== "number") {
      list = list.slice();
      if (sort === "name") {
        list.sort(function (a, b) { return String(a.name || "").localeCompare(String(b.name || "")); });
      } else {
        var desc = sort === "priceDesc";
        list.sort(function (a, b) {
          var am = marketOf(a), bm = marketOf(b);
          if (am === null && bm === null) return 0;
          if (am === null) return 1;
          if (bm === null) return -1;
          return desc ? bm - am : am - bm;
        });
      }
    }
    var start = (page - 1) * pageSize;
    return {
      data: list.slice(start, start + pageSize),
      totalCount: list.length,
      page: page,
      pageSize: pageSize
    };
  }

  /* Distinct rarities in a set, in order of first appearance — that
   * follows set-number order, so commons come first. Cards without a
   * rarity read as "Unknown". */
  async function getSetRarities(appId) {
    var list = await getSetCardList(appId);
    var seen = {}, out = [];
    list.forEach(function (c) {
      var r = c.rarity || "Unknown";
      if (!seen[r]) { seen[r] = true; out.push(r); }
    });
    return out;
  }

  /* ---------------- card detail ---------------- */

  var detailCache = {};
  async function getCard(id, lang) {
    lang = lang || "en";
    var key = lang + ":" + id;
    if (detailCache[key]) return detailCache[key];
    var raw = null, setId = "", setName = "";
    if (lang === "ja") {
      /* Japanese cards: prefer the local snapshot. Live TCGdex carries
       * no tcgplayer pricing for Japanese printings, while snapshots
       * carry the baked PkmnPrices catalog prices the tiles already use.
       * Falls back to the live API for cards added after the snapshot. */
      try {
        var setIdGuess = id.slice(0, Math.max(0, id.lastIndexOf("-")));
        if (setIdGuess) {
          var snap = await snapJson(setSnapPath("ja-" + setIdGuess));
          (snap.cards || []).some(function (sc) {
            if (sc.id === id) { raw = sc; return true; }
            return false;
          });
          if (raw) {
            setId = (snap.set && snap.set.id) || setIdGuess;
            setName = (snap.set && snap.set.name) || "";
          }
        }
      } catch { raw = null; }
    }
    if (!raw) {
      var c = await req("/cards/" + encodeURIComponent(id), lang);
      raw = c;
      setId = (c.set && c.set.id) || id.slice(0, Math.max(0, id.lastIndexOf("-")));
      setName = (c.set && c.set.name) || "";
    }
    var card = normCard(raw, setId, setName, lang);
    detailCache[key] = card;
    return card;
  }

  /* Fetch details for many ids with bounded parallelism; failures resolve
   * to null instead of rejecting the batch. */
  async function getDetails(ids, limit, lang) {
    limit = limit || 8;
    var out = new Array(ids.length);
    var i = 0;
    async function worker() {
      while (i < ids.length) {
        var k = i++;
        try { out[k] = await getCard(ids[k], lang); }
        catch { out[k] = null; }
      }
    }
    var ws = [];
    for (var w = 0; w < Math.min(limit, ids.length); w++) ws.push(worker());
    await Promise.all(ws);
    return out;
  }

  /* ---------------- search ---------------- */

  var indexCache = null;
  async function getIndex() {
    if (indexCache) return indexCache;
    var combined = [];
    try {
      var snap = await snapJson("index.json");
      if (Array.isArray(snap) && snap.length) {
        snap.forEach(function (e) { e.lang = "en"; combined.push(e); });
      }
    } catch { /* no snapshot: live API below */ }
    /* Japanese snapshot index: English name + Japanese name + illustrator */
    try {
      var jaSnap = await snapJson("index-ja.json");
      if (Array.isArray(jaSnap) && jaSnap.length) {
        jaSnap.forEach(function (e) { e.lang = "ja"; combined.push(e); });
      }
    } catch { /* no JA index yet */ }
    if (combined.length) { indexCache = combined; return combined; }
    try {
      var raw = localStorage.getItem(LS_INDEX);
      if (raw) {
        var p = JSON.parse(raw);
        if (p && Array.isArray(p.cards) && p.cards.length && (Date.now() - (p.at || 0)) < CACHE_TTL) {
          indexCache = p.cards;
          return p.cards;
        }
      }
    } catch { /* corrupted: refetch below */ }
    var arr = await req("/cards"); // [{id, localId, name}], ~23k cards, one request
    indexCache = arr;
    try { localStorage.setItem(LS_INDEX, JSON.stringify({ at: Date.now(), cards: arr })); } catch { /* quota: memory cache still works */ }
    return arr;
  }

  var setRankCache = null;
  async function getSetRank() {
    if (setRankCache) return setRankCache;
    var sets = await getSets(); // newest first
    var rank = {};
    /* Keyed by app id ("ja-…" for Japanese): raw ids like neo1 exist in
     * both languages and must not collide. */
    sets.forEach(function (s, i) { rank[appSetId(s.lang, s.id)] = i; });
    setRankCache = rank;
    return rank;
  }

  function setIdOf(entryId) {
    var d = String(entryId).lastIndexOf("-");
    return d > 0 ? entryId.slice(0, d) : "";
  }

  /* Fetch card details for index entries that may mix English and
   * Japanese cards, preserving order; failures resolve to null. */
  async function getDetailsMixed(entries, limit) {
    var groups = {};
    entries.forEach(function (e) {
      var l = e.lang === "ja" ? "ja" : "en";
      (groups[l] = groups[l] || []).push(e);
    });
    var byKey = {};
    await Promise.all(Object.keys(groups).map(function (l) {
      var ids = groups[l].map(function (e) { return e.id; });
      return getDetails(ids, limit, l).then(function (ds) {
        ids.forEach(function (id, i) { byKey[l + ":" + id] = ds[i]; });
      });
    }));
    return entries.map(function (e) {
      var l = e.lang === "ja" ? "ja" : "en";
      return byKey[l + ":" + e.id];
    }).filter(Boolean);
  }

  /* Structured search over the cached full-card index. Name/set filter
   * against the index; artist/rarity/type/value need card details, so
   * those fetch details for the top matches (capped) before paginating.
   * Returns {data, totalCount, page, pageSize, truncated}. */
  async function searchCards(opts) {
    opts = opts || {};
    var page = opts.page || 1;
    var pageSize = opts.pageSize || 24;
    var idx = await getIndex();

    var nameQ = String(opts.name || "").trim().toLowerCase();
    var artistQ = String(opts.artist || "").trim().toLowerCase();
    var setId = String(opts.setId || "").trim();
    var rarityQ = String(opts.rarity || "").trim();
    var typeQ = String(opts.type || "").trim();
    var min = (opts.min === "" || opts.min == null) ? null : parseFloat(opts.min);
    var max = (opts.max === "" || opts.max == null) ? null : parseFloat(opts.max);
    if (min !== null && isNaN(min)) min = null;
    if (max !== null && isNaN(max)) max = null;

    var matches = idx.filter(function (e) {
      if (setId && setIdOf(e.id) !== setId) return false;
      if (nameQ) {
        /* Match English name, Japanese name, and illustrator, so queries
         * like "yu nagaba" find the cards they illustrated. */
        var hay = (String(e.name || "") + " " + String(e.nameJa || "") + " " + String(e.illustrator || "")).toLowerCase();
        if (hay.indexOf(nameQ) === -1) return false;
      }
      return true;
    });

    var needDetails = !!(artistQ || rarityQ || typeQ || min !== null || max !== null);
    var truncated = false;
    var data, totalCount;

    if (needDetails) {
      var cands = matches.slice(0, DETAIL_CAP);
      truncated = matches.length > DETAIL_CAP;
      var details = await getDetailsMixed(cands);
      var filtered = [];
      details.forEach(function (d) {
        if (!d) return;
        if (artistQ && String(d.artist || "").toLowerCase().indexOf(artistQ) === -1) return;
        if (rarityQ && d.rarity !== rarityQ) return;
        if (typeQ && (d.types || []).indexOf(typeQ) === -1) return;
        var m = marketOf(d);
        if (min !== null && (m === null || m < min)) return;
        if (max !== null && (m === null || m > max)) return;
        filtered.push(d);
      });
      totalCount = filtered.length;
      data = filtered.slice((page - 1) * pageSize, page * pageSize);
    } else {
      totalCount = matches.length;
      var ranked = matches;
      if (!nameQ && !setId) {
        // unfiltered browse: newest sets first, then card number
        var rank = await getSetRank();
        ranked = matches.slice().sort(function (a, b) {
          var ra = rank[appSetId(a.lang, setIdOf(a.id))], rb = rank[appSetId(b.lang, setIdOf(b.id))];
          ra = ra === undefined ? 1e9 : ra;
          rb = rb === undefined ? 1e9 : rb;
          if (ra !== rb) return ra - rb;
          var an = parseInt(a.localId, 10), bn = parseInt(b.localId, 10);
          if (!isNaN(an) && !isNaN(bn) && an !== bn) return an - bn;
          return 0;
        });
      }
      var pageEntries = ranked.slice((page - 1) * pageSize, page * pageSize);
      data = await getDetailsMixed(pageEntries);
    }

    return { data: data, totalCount: totalCount, page: page, pageSize: pageSize, truncated: truncated };
  }

  /* ---------------- prices (TCGPlayer, via TCGdex) ---------------- */

  /* Best available TCGPlayer market price across print variants. */
  function marketOf(card) {
    var prices = card && card.tcgplayer && card.tcgplayer.prices;
    if (!prices) return null;
    var best = null;
    ["holofoil", "reverseHolofoil", "normal"].forEach(function (v) {
      var m = prices[v] && prices[v].market;
      if (typeof m === "number") best = best === null ? m : Math.max(best, m);
    });
    return best;
  }

  /* Shared: App.util.VARIANT_LABELS (js/util.js). */
  var VARIANT_LABELS = App.util.VARIANT_LABELS;

  /* Available print variants with their price blocks, highest-market first. */
  function variantsOf(card) {
    var prices = card && card.tcgplayer && card.tcgplayer.prices;
    if (!prices) return [];
    return Object.keys(VARIANT_LABELS)
      .filter(function (v) { return prices[v]; })
      .map(function (v) {
        return { key: v, label: VARIANT_LABELS[v], prices: prices[v] || {} };
      })
      .sort(function (a, b) {
        return (b.prices.market || -1) - (a.prices.market || -1);
      });
  }

  /* ---------------- print variants (pkmn.gg-style checkboxes) ---------------- */

  /* Canonical variant-label normalizer, shared by set tiles and collection
   * rows. "Poké Ball" -> "pokeball"; "Energy Symbol Pattern" -> "energy";
   * "Holofoil" -> "holo"; "Standard" -> "normal". */
  function normVLabel(s) {
    var t = String(s || "").toLowerCase();
    try { t = t.normalize("NFD").replace(/[\u0300-\u036f]/g, ""); } catch { /* no normalize */ }
    t = t.replace(/[^a-z0-9]/g, "");
    if (t === "standard") return "normal";
    if (t === "holofoil") return "holo";
    if (t === "reverseholofoil" || t === "reverseholo") return "reverse";
    if (t.indexOf("energy") === 0) return "energy";
    return t;
  }

  var FOIL_LABELS = { pokeball: "Poké Ball", energy: "Energy Symbol" };
  /* PkmnPrices record-name parenthetical for a TCGdex foil, for exact-record
   * matching: "pokeball" -> "poke ball" matches "(Poke Ball)". */
  var FOIL_PKMN_LABELS = { pokeball: "poke ball", energy: "energy symbol pattern" };

  /* Foil printings outside the reverse slot: TCGdex marks them as
   * {type:"holo", foil:"cosmos"} (or type "normal"/"metal" + foil). They
   * used to collapse onto the plain "Holo"/"Normal" checkbox — same vlabel —
   * so checking one box checked the other (e.g. Vileplume me02-003, 1st and
   * 3rd boxes; 748 cards catalog-wide). Each foil now gets its own label:
   * "Cosmos Holo" for holo printings, "<Foil> Foil" otherwise. */
  var FOIL_WORDS = {
    cosmos: "Cosmos",
    galaxy: "Galaxy",
    starlight: "Starlight",
    "cracked-ice": "Cracked Ice",
    energy: "Energy",
    mirror: "Mirror",
    league: "League",
    gold: "Gold",
    tinsel: "Tinsel",
    rainbow: "Rainbow"
  };
  function foilWords(foil) {
    if (FOIL_WORDS[foil]) return FOIL_WORDS[foil];
    return String(foil || "").split("-").map(function (w) {
      return w.charAt(0).toUpperCase() + w.slice(1);
    }).join(" ");
  }

  /* One checkbox per actual printing, from TCGdex variants_detailed (free,
   * no API credits — and present in the local snapshot). Each entry:
   * { key, label, vlabel, pkmnLabel, priceVariant }. */
  function printVariants(card) {
    var vd = card && card.variants_detailed;
    if (!Array.isArray(vd) || !vd.length) return [];
    /* Dedupe identical (type, foil) entries: TCGdex repeats them for some
     * cards (e.g. base1 holos list {type:"holo",foil:null} four times for
     * the edition variants). Identical entries would render identical
     * checkboxes sharing one vlabel — the same "checking one checks the
     * other" bug as the foil collapse. */
    var seen = {};
    var out = [];
    vd.forEach(function (v) {
      var type = String((v && v.type) || "").toLowerCase();
      var foil = String((v && v.foil) || "").toLowerCase();
      var key = foil ? type + ":" + foil : type;
      if (seen[key]) return;
      seen[key] = true;
      var r = { key: key };
      if (type === "reverse" && foil) {
        r.label = FOIL_LABELS[foil] || (foil.charAt(0).toUpperCase() + foil.slice(1));
        r.pkmnLabel = FOIL_PKMN_LABELS[foil] || null;
        r.priceVariant = "reverseHolofoil";
      } else if (type === "reverse") {
        r.label = "Reverse Holo";
        r.pkmnLabel = "reverse holo";
        r.priceVariant = "reverseHolofoil";
      } else if (type === "holo") {
        if (foil) {
          r.label = foilWords(foil) + " Holo";
          r.pkmnLabel = foilWords(foil).toLowerCase() + " holo";
          r.priceVariant = "holofoil";
        } else {
          r.label = "Holo";
          r.pkmnLabel = null;
          r.priceVariant = "holofoil";
        }
      } else {
        if (foil) {
          r.label = foilWords(foil) + " Foil";
          r.pkmnLabel = foilWords(foil).toLowerCase() + " foil";
          r.priceVariant = "normal";
        } else {
          r.label = "Normal";
          r.pkmnLabel = null;
          r.priceVariant = "normal";
        }
      }
      r.vlabel = normVLabel(r.label);
      out.push(r);
    });
    return out;
  }

  /* Map a collection row's variant label to its PkmnPrices match hints. */
  function printVariantForLabel(label) {
    var v = normVLabel(label);
    if (v === "pokeball") return { pkmnLabel: "poke ball", priceVariant: "reverseHolofoil" };
    if (v === "energy") return { pkmnLabel: "energy symbol pattern", priceVariant: "reverseHolofoil" };
    if (v === "reverse") return { pkmnLabel: "reverse holo", priceVariant: "reverseHolofoil" };
    if (v === "holo") return { pkmnLabel: null, priceVariant: "holofoil" };
    /* Foil printings from printVariants ("<Foil> Holo" / "<Foil> Foil").
     * pkmnLabel matches a PkmnPrices record parenthetical when one exists
     * (e.g. "(Cosmos Holo)"); otherwise findVariantPrice falls back to the
     * base record and prices the holofoil/normal finish. */
    for (var slug in FOIL_WORDS) {
      var words = FOIL_WORDS[slug];
      if (v === normVLabel(words + " Holo"))
        return { pkmnLabel: words.toLowerCase() + " holo", priceVariant: "holofoil" };
      if (v === normVLabel(words + " Foil"))
        return { pkmnLabel: words.toLowerCase() + " foil", priceVariant: "normal" };
    }
    return { pkmnLabel: null, priceVariant: "normal" };
  }

  App.tcg = {
    searchCards: searchCards,
    getCard: getCard,
    getDetails: getDetails,
    getSets: getSets,
    getSet: getSet,
    getSetCards: getSetCards,
    getSetCardList: getSetCardList,
    getSetRarities: getSetRarities,
    parseSetId: parseSetId,
    marketOf: marketOf,
    variantsOf: variantsOf,
    printVariants: printVariants,
    printVariantForLabel: printVariantForLabel,
    normVLabel: normVLabel,
    normNumber: normNumber,
    ApiError: ApiError
  };
})();
